name: generate plantuml
on:
  push:
    branches:
      - master
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: plantuml
        id: plantuml
        uses: moisespsena/generate-plantuml-action@master
        with:
          path: example/default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: plantuml-png
        id: plantuml
        uses: moisespsena/generate-plantuml-action@master
        with:
          path: example/png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
